ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit hooks

        For more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit.ci autoupdate (for more information, see https://pre-commit.ci)'
    autoupdate_schedule: monthly
    skip: []
    submodules: false

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.5.5'
    hooks:
      # Run the linter.
      - id: ruff
        args: ['--fix']
      # Run the formatter.
      - id: ruff-format